on:
  workflow_dispatch:
  push:

name: test-basiliskStart-fallback

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc }}

    strategy:
      fail-fast: false
      matrix:
        config:
        # - { os: macOS-latest, bioc: 'devel'}
        # - { os: ubuntu-latest, bioc: 'devel'}
        - { os: macOS-latest, bioc: 'release'}
        - { os: ubuntu-latest, bioc: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc }}

      - name: Install basilisk
        run: |
          BiocManager::install(c('basilisk'))
        shell: Rscript {0}

      - name: Test basiliskStart
        run: |
          library(basilisk)
          library(basilisk.utils)
          basilisk.utils::installConda()

          basilisk::setBasiliskForceFallback(TRUE)

          tmploc <- file.path(tempdir(), "my_package_A")
          if (!file.exists(tmploc)) {
              setupBasiliskEnv(tmploc, c('pandas=1.4.3'))
          }
          cl <- basiliskStart(tmploc, testload="pandas")
          cl

          .libPaths()
          sessionInfo()
        shell: Rscript {0}
